openapi: 3.0.0

info:
  title: Abarrotes Usuarios API
  version: '1.0.0'
  description: API para registrar, validar y autenticar usuarios

paths:
  /usuarios/registrar:
    post:
      summary: Registrar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuario registrado con éxito
  /usuarios/validar:
    post:
      summary: Validar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuario validado con éxito
  /usuarios/login:
    post:
      summary: Login usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuario autenticado con éxito

components:
  schemas:
    UserRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
