openapi: 3.0.0

info:
  title: Abarrotes Usuarios API
  version: '1.0.0'
  description: API para registrar, validar y autenticar usuarios

paths:
  /usuarios/registrar:
    post:
      summary: Registrar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuario registrado con éxito
  /usuarios/validar:
    post:
      summary: Validar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuario validado con éxito
  /usuarios/login:
    post:
      summary: Login usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuario autenticado con éxito

components:
  schemas:
    UserAccessRequest:
      type: object
      properties:
        user_id:
          type: string
          description: "User ID (correo electrónico)"
        tenant_id:
          type: string
          description: "Tenant ID (nombre del establecimiento)"
        password:
          type: string
          description: "User password"
    UserValidateRequest:
      type: object
      properties:
        token:
          type: string
          description: "Token por validar al lambda authorizer"
        tenant_id:
          type: string
          description: "Tenant ID (nombre del establecimiento)"
