org: salvadordonayre
service: abarrotes-compras

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: false

provider:
  name: aws
  runtime: python3.12
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::107956752347:role/LabRole


functions:
  registrar:
    handler: AddProduct.lambda_handler
    events:
      - http:
          path: /cart/add
          method: post
          cors: true
          integration: lambda


