org: salvadordonayre
service: abarrotes-compras

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: false

provider:
  name: aws
  runtime: python3.12
  timeout: 30
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::107956752347:role/LabRole
  environment:
    stage: ${self:provider.stage}
    TABLE_NAME: ${self:provider.stage}-t-carrito


functions:
  anadir:
    handler: AddProduct.lambda_handler
    events:
      - http:
          path: /cart/add
          method: post
          cors: true
          integration: lambda-proxy
  actualizar:
    handler: UpdateProduct.lambda_handler
    events:
      - http:
          path: /cart/update
          method: put
          cors: true
          integration: lambda-proxy 
  eliminar:
    handler: DeleteProduct.lambda_handler
    events:
      - http:
          path: /cart/delete
          method: delete
          cors: true
          integration: lambda-proxy 
  listar:
    handler: GetCart.lambda_handler
    events:
      - http:
          path: /cart
          method: get
          cors: true
          integration: lambda-proxy
  confirm:
    handler: CompletePurchase.lambda_handler
    events:
      - http:
          path: /cart/complete
          method: post
          cors: true
          integration: lambda-proxy 

resources:
  Resources:
    CartTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    HistoryCartTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}-history
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: compra_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: compra_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

  



