service: abarrotes-streams
org: salvadordonayre

plugins:
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  stage: ${self:custom.stage}
  iam:
    role: arn:aws:iam::107956752347:role/LabRole
  environment:
    STAGE: ${self:custom.stage}
    ES_ENDPOINT: ${self:custom.esEndpoint}
    TABLE_AUTH: ${self:custom.tableAuth}
    TABLE_USER: ${self:custom.tableUser}
    TABLE_PRODUCTOS: ${self:custom.tableProductos}
    TABLE_CARRITO: ${self:custom.tableCarrito}
    TABLE_CARRITO_HISTORIAL: ${self:custom.tableCarritoHistorial}

custom:
  stage: ${opt:stage, 'dev'}
  esEndpoint: http://3.90.86.225:9200
  tableUser: ${sls:stage}_ab_usuarios
  tableAuth: ${sls:stage}_ab_tokens_acceso
  tableProductos: ${sls:stage}_ab_productos
  tableCarrito: ${sls:stage}_ab_carrito
  tableCarritoHistorial: ${sls:stage}_ab_carrito
  flowProductos: 2025-07-09T15:11:59.272

functions:
  product-insert:
    handler: ProductInsert.handler
    environment:
      ES_ENDPOINT: ${self:custom.esEndpoint}
      INDEX_NAME: ${self:custom.stage}_ab_productos
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:us-east-1:107956752347:table/${self:custom.tableProductos}/stream/${flowProductos}
          batchSize: 5
          startingPosition: LATEST