service: abarrotes-streams
org: salvadordonayre

plugins:
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  stage: ${self:custom.stage}
  iam:
    role: arn:aws:iam::664631149389:role/LabRole
  environment:
    STAGE: ${self:custom.stage}
    ES_ENDPOINT: ${self:custom.esEndpoint}
    TABLE_AUTH: ${self:custom.tableAuth}
    TABLE_USER: ${self:custom.tableUser}
    TABLE_PRODUCTOS: ${self:custom.tableProductos}
    TABLE_CARRITO: ${self:custom.tableCarrito}
    TABLE_CARRITO_HISTORIAL: ${self:custom.tableCarritoHistorial}

custom:
  unused: "XD"
  stage: ${opt:stage, 'dev'}
  esEndpoint: http://3.95.184.197:9200
  tableUser: ${sls:stage}_ab_usuarios
  tableAuth: ${sls:stage}_ab_tokens_acceso
  tableProductos: ${sls:stage}_ab_productos
  tableCarrito: ${sls:stage}_ab_carrito
  tableCarritoHistorial: ${sls:stage}_ab_carrito
  arnProductos: arn:aws:dynamodb:us-east-1:250853414258:table/dev_ab_productos/stream/2025-07-13T20:58:12.144

functions:
  product-insert: 
    handler: ProductInsert.handler
    environment:
      ES_ENDPOINT: ${self:custom.esEndpoint}
      INDEX_NAME: ${self:custom.stage}_ab_productos
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.arnProductos}
          batchSize: 5
          startingPosition: LATEST