org: salvadordonayre
service: abarrotes-productos

plugins:
  - serverless-aws-documentation

custom:
  stage: ${opt:stage, 'dev'}
  documentation:
    apiInfo:
      version: '1.0.0'
      title: Abarrotes Productos API
      description: API para crear, buscar, listar, modificar y eliminar productos
    models:
      - name: ProductRequest
        contentType: 'application/json'
        schema:
          type: object
          properties:
            producto_id:
              type: string
              description: "ID único del producto"
            tenant_id:
              type: string
              description: "ID del tenant"
            nombre:
              type: string
              description: "Nombre del producto"
            precio:
              type: number
              format: float
              description: "Precio del producto"
            stock:
              type: integer
              description: "Cantidad en stock"

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  stage: ${self:custom.stage}
  iam:
    role: arn:aws:iam::107956752347:role/LabRole
  environment:
    STAGE: ${self:custom.stage}

functions:
  crear:
    handler: handlers/ProductCreate.handler
    documentation:
      summary: Crear producto
      requestModels:
        'application/json': ProductRequest
    events:
      - http:
          path: /productos/crear
          method: post
          cors: true

  buscar:
    handler: handlers/ProductGet.handler
    documentation:
      summary: Buscar producto
    events:
      - http:
          path: /productos/buscar
          method: get
          cors: true

  listar:
    handler: handlers/ProductList.handler
    documentation:
      summary: Listar productos
    events:
      - http:
          path: /productos/listar
          method: get
          cors: true

  modificar:
    handler: handlers/ProductModify.handler
    documentation:
      summary: Modificar producto
      requestModels:
        'application/json': ProductRequest
    events:
      - http:
          path: /productos/modificar
          method: patch
          cors: true

  eliminar:
    handler: handlers/ProductDelete.handler
    documentation:
      summary: Eliminar producto
      requestModels:
        'application/json': ProductRequest
    events:
      - http:
          path: /productos/eliminar
          method: delete
          cors: true

  swaggerui:
    handler: handlers/swagger.lambda_handler
    events:
      - http:
          path: /docs
          method: get
          cors: true

  openapi:
    handler: handlers/swagger.openapi_handler
    events:
      - http:
          path: /openapi.yaml
          method: get
          cors: true
