org: salvadordonayre
service: abarrotes-productos

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  iam:
    role: arn:aws:iam::107956752347:role/LabRole

functions:
  crear:
    handler: ProductCreate.handler
    events:
      - http:
          path: /productos/crear
          method: post
          cors: true
          integration: lambda
